rewards:

rewards-lose:

# If command is used, fill command with command that will be executed by console
# If location is used, fill location with location
spawn_teleport:
  use: 'prior' # 'command' or 'location' or 'prior'
  command: 'tp %player%'
  location:
    world: 'world'
    x: 0.0
    y: 0.0
    z: 0.0

elo-scoreboard: true # Whether to enable the scoreboard for player rankings.

custom-enchants:
  schrodingers-instant-death:
    potion-effect: 'HARMING:100:100'
    target: 'RANDOM'
    chance: 1.0
    cooldown: 10
    message: '<red>You have observed the cat, meow!'
    lightning-strike: false
    name: '<red>Schrodingers Instant Death'
    lore:
      - '<red>Chance: 100%'
      - '<red>Cooldown: 10 seconds'
      - '<red>Target: Random'

cooldown:
  before: 5 # seconds
  after: 5 # seconds

messages:
  bad_usage: '<red>Invalid usage'
  no_permission: "<red>You don't have permission to execute this command"
  arena:
    not_yours: '<red>Arena is not yours'
    not_found: '<red>Arena not found'
    help:
      - '<yellow><bold>Arena Help'
      - '<green>/arena list - Show your arenas'
      - '<green>/arena delete <name> - Delete your arena'
      - '<green>/arena public <name> - Make arena public/private'
      - '<yellow>How to create a new arena:'
      - '<gold>1. <green>/arena create <name> - Create a new arena'
      - '<gold>2. <green>/arena sp1 <name> - Set spawn point for the first player'
      - '<gold>3. <green>/arena sp2 <name> - Set spawn point for the second player'
    public_command:
      success_private: '<green>Arena made private'
      success_public: '<green>Arena made public'
    list:
      - '<yellow><bold>Your arenas:'
      - '<green>%arenas%'
    delete:
      delete: '<green>Arena deleted'
      running: "<green>Arena is in use; you can't delete it"
    create:
      exists: '<red>Arena already exists'
      success: '<green>Arena created! Now you can change the spawn points for the players with /arena sp1 and /arena sp2 respectively'
      no_name: '<red>You need to specify a name'
      alphanumeric: '<red>Name must only contain letters and numbers'
      banned: '<red>You are banned from making arenas'
    sp1:
      success: '<green>Spawn point set for the first player!'
    sp2:
      success: '<green>Spawn point set for the second player!'
    totems:
        enabled: '<green>Totems have been enabled for this arena'
        disabled: '<green>Totems have been <red>disabled<green> for this arena'
  pvp:
    help:
      - '<yellow><bold>PVP Help'
      - '<green>/pvp - Show help'
      - '<green>/pvp <player> - Invite a player to a 1v1 fight'
      - '<green>/pvp accept - Accept a 1v1 fight (alternative for clickable message)'
    invite:
      player_offline: '<red>Player is offline'
      invite_self: "<red>You can't invite yourself"
      invite_sent: '<green>Invite was sent to %player%'
    scoreboard:
      enabled: '<green>Scoreboard enabled'
      disabled: '<green>Scoreboard disabled'
    banned:
      cant_invite: '<red>You are banned from making PVP fights'
      cant_accept: '<red>You are banned from accepting PVP fights'
  mod:
    help:
      - '<yellow><bold>Mod Help'
      - '<green>/mod - Show help'
      - '<green>/mod ban arena - Toggle ban player from making arenas'
      - '<green>/mod ban pvp - Toggle ban player from making PVP fights'
    ban:
      arena:
        banned: '<green>%player% banned from making arenas'
        unbanned: '<green>%player% unbanned from making arenas'
      pvp:
        banned: '<green>%player% banned from making PVP fights'
        unbanned: '<green>%player% unbanned from making PVP fights'
  arena_select_gui:
    inventory_name: '<yellow><bold>SELECT ARENA TO FIGHT'
    arena_item:
      item: 'GRASS_BLOCK'
      name: '<green>%arena_name%'
      lore:
        - '<yellow><bold>Arena name: <green>%arena_name%'
        - '<yellow><bold>Arena owner: <green>%arena_owner%'
        - '<yellow><bold>Totems: %totemsenabled%'
    arena_not_ready: '<red>Arena is not ready'
    invite_message: '<green>Click <white><hover:show_text:"<green>Click to accept the pvp match!"><click:run_command:/pvp accept>[here]</click></hover> <green>to join PVP arena with %inviter% in %arena_name%, totems are %totems% you have a %winchance% chance of winning!'
  totem_select_gui:
    inventory_name: '<yellow><bold>ENABLE TOTEMS?'
    items:
      enable:
        item: 'GREEN_STAINED_GLASS_PANE'
        name: '<green>Enable totems'
        lore:
          - '<yellow><bold>Click to enable totems'
      disable:
        item: 'RED_STAINED_GLASS_PANE'
        name: '<red>Disable totems'
        lore:
          - '<yellow><bold>Click to disable totems'
  gvg:
    help:
      - '<yellow><bold>Group Help'
      - '<green>/gvg <player> - Invite a player to a group fight'
      - '<green>/gvg invite <player> [player]... - Invite player/s to a group fight'
      - '<green>/gvg leave - Leave the group'
      - '<green>/gvg kick <player> - Kick a player from the group'
    dont_have_group: '<red>You are not the owner of your group'
    not_in_group: '<red>You are not in the group'
    player_offline: '<red>Player %player% is offline'
    you_left: '<green>You left the group'
    player_not_in_group: '<red>Player is not in the group or is in your group'
    invite:
      already_in_group: '<red>Player %player% is already in the group'
      invite_message: '<green>Click <white><hover:show_text:"<green>Click to accept the group invite!"><click:run_command:/gvg accept>[here]</click></hover><green> to accept the group invite!'
      invite_yourself: "<red>You can't invite yourself"
      invite_sent: '<green>Invite was sent to %player%'
      cant_invite_yourself: "<red>You can't invite yourself"
    accept:
      invite_not_found: '<red>Invite not found'
      you_already_in_group: '<red>You are already in the group'
      accepted: '<green>Invite accepted'
      invite_accepted: '<green>%player% accepted an invite to the group'
    leave:
      player_left_group: '<green>%player% left the group'
    kick:
      not_in_group: "<red>You are not in the group or you don't have permission"
      player_not_in_group: '<red>Player is not in the group'
      you_kicked: '<red>You were kicked from the group'
      kicked: '<green>%player% was kicked from the group'
  invite_accept:
    invite_not_found: '<red>Invite not found'
    invite_already_accepted: '<red>Invite already accepted'
    other_player_offline: '<red>Player is offline'
    arena_not_ready: '<red>Arena is not ready right now! Try again later'
    group:
      group_not_found: '<red>Group not found'
      group_too_small: '<red>Group is too small'
      someone_already_in_fight: '<red>Someone is already in a fight'
  fight:
    starting: '<green>%time%'
    started: '<green>Fight started!'
    totems_enabled: '<green>Totems enabled!'
    totems_disabled: '<red>Totems disabled!'
    problem_saving_inventories: '<red>Problem saving inventories'
    end: '<green>Fight ended! Winner: %winner%, teleporting in %time% seconds'
    end_global: '<green>%winner% just slaughtered %loser% in the %arena% arena with a win chance of %winchance%%!'
  market:
    help:
      - '<yellow><bold>Market Help'
      - '<green>/market - Open the market'
      - '<green>/market sell <price> - Sell the currently held item for the specified price'
      - '<green>/market buy - Open the market'
    create:
      success: '<green>Item added to the market'
      fail: '<red>Fail???? Pls fix me, tell axo about this'
      no_item: '<red>Item not found'
    item_lore:
      - '<yellow><bold>Price: <green>%price%'
      - '<yellow><bold>Click to buy'
    inventory_name: '<yellow><bold>MARKET'
    item_bought: '<green>You bought %item% for %price%'
    item_not_found: '<red>Item not found'
  profile:
    - '<yellow><bold>Profile of %player%'
    - '<yellow><bold>ELO: <green>%elo%'
    - '<yellow><bold>Games: <green>%games%'
    - '<yellow><bold>Wins: <green>%wins%'
    - '<yellow><bold>Losses: <green>%losses%'
    - '<yellow><bold>PVP-Banned: <green>%pvpbanned%'
    - '<yellow><bold>Arena-Banned: <green>%arenabanned%'
  scoreboard:
    top: '<yellow><bold>Top 10 players in PVP'
