name: Double
version: ${version}
main: dev.xdbl.Double
api-version: '1.21'
description: Double, the utility plugin.
author: Axodouble
website: https://github.com/Axodouble/Double
commands:
  arena:
    description: Arena command
    usage: /arena <list|delete|public> [name]
    permission: xdbl.arena
    permission-message: "You do not have permission to use this command"
  pvp:
    description: PVP command
    usage: /pvp <player|accept>
    permission: xdbl.pvp
    permission-message: "You do not have permission to use this command"
  gvg:
    description: GVG command
    usage: /gvg <player|accept|invite>
    permission: xdbl.gvg
    permission-message: "You do not have permission to use this command"
  mod:
    description: Moderation commands
    usage: /mod <ban> <arena|pvp> <player>
    permission: xdbl.mod
    permission-message: "You do not have permission to use this command"
  leaderboard:
    description: Show the top fighters in the server
    usage: /leaderboard
    permission: xdbl.pvp
    aliases: [ top ]
    permission-message: "You do not have permission to use this command"
  profile:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
    permission-message: "You do not have permission to use this command"
  stats:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
    permission-message: "You do not have permission to use this command"
  version:
    description: Show the plugin version
    usage: /version
  sit:
    description: Sit command
    usage: /sit
    permission: xdbl.sit
    permission-message: "You do not have permission to use this command"
  marry:
    description: Marry command
    usage: /marry <player>
    permission: xdbl.marry
    permission-message: "You do not have permission to use this command"
  divorce:
    description: Divorce command
    usage: /divorce
    permission: xdbl.marry
    permission-message: "You do not have permission to use this command"
  accept:
    description: Accept command
    usage: /accept
    permission: xdbl.marry
    permission-message: "You do not have permission to use this command"
  jump:
    description: Jump command
    usage: /jump
    permission: xdbl.jump
    aliases: [ j ]
    permission-message: "You do not have permission to use this command"
  day:
    description: Day command
    usage: /day
    permission: xdbl.time.day
    permission-message: "You do not have permission to use this command"
  night:
    description: Night command
    usage: /night
    permission: xdbl.time.night
    permission-message: "You do not have permission to use this command"
  discord:
    description: Discord command
    usage: /discord
    permission: xdbl.discord
    permission-message: "You do not have permission to use this command"
  race:
    description: A command to change your race
    usage: /race
    permission: xdbl.races
    permission-message: "You do not have permission to use this command"
permissions :
  xdbl.discord:
    description: "Access to the /discord command that is set in the config.yml"
    default: not op
  xdbl.time:
    description: "Access to the /day and /night commands"
    default: op
    children:
      xdbl.time.day:
        description: "Access to the /day command"
        default: op
      xdbl.time.night:
        description: "Access to the /night command"
        default: op
      xdbl.time.*:
        description: "Access to all time commands"
        default: op
  xdbl.arena:
    description: "Access to the /arena command"
    default: not op
  xdbl.pvp:
    description: "Access to the /pvp command"
    default: not op
  xdbl.gvg:
    description: "Access to the /gvg command"
    default: not op
  xdbl.mod:
    description: "Access to the /mod command"
    default: op
  xdbl.sit:
    description: "Access to the /sit command and to sit on blocks"
    default: not op
  xdbl.marry:
    description: "Access to the /marry, /accept and /divorce commands"
    default: not op
  xdbl.jump:
    description: "Access to the /jump command"
    default: op
  xdbl.races:
    description: "Access to the /race command"
    default: not op
    children:
      xdbl.races.become:
        description: "Access to become a race with /race become <race>"
        default: not op
      xdbl.races.become.*:
        description: "Access to specific races"
        default: not op
      xdbl.races.reload:
        description: "Access to reload the races"
        default: op
      xdbl.races.restore:
        description: "Access to restore all races"
        default: op