name: Double
version: ${version}
main: dev.xdbl.Double
api-version: '1.21'
commands:
  arena:
    description: Arena command
    usage: /arena <list|delete|public> [name]
    permission: xdbl.arena
  pvp:
    description: PVP command
    usage: /pvp <player|accept>
    permission: xdbl.pvp
  gvg:
    description: GVG command
    usage: /gvg <player|accept|invite>
    permission: xdbl.gvg
  mod:
    description: Moderation commands
    usage: /mod <ban> <arena|pvp> <player>
    permission: xdbl.mod
  leaderboard:
    description: Show the top fighters in the server
    usage: /leaderboard
    permission: xdbl.pvp
    aliases: [ top ]
  profile:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
  stats:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
  version:
    description: Show the plugin version
    usage: /version
  kingdom:
    description: Kingdom related commands
    usage: /kingdom
    permission: xdbl.kingdom
  sit:
    description: Sit command
    usage: /sit
    permission: xdbl.sit
  marry:
    description: Marry command
    usage: /marry <player>
    permission: xdbl.marry
  divorce:
    description: Divorce command
    usage: /divorce
    permission: xdbl.marry
  accept:
    description: Accept command
    usage: /accept
    permission: xdbl.accept
  jump:
    description: Jump command
    usage: /jump
    permission: xdbl.jump
    aliases: [ j ]
  day:
    description: Day command
    usage: /day
    permission: xdbl.time
  night:
    description: Night command
    usage: /night
    permission: xdbl.time
  discord:
    description: Discord command
    usage: /discord
    permission: xdbl.discord
