name: Double
version: ${version}
main: dev.xdbl.Double
api-version: '1.20'
commands:
  arena:
    description: Arena command
    usage: /arena <list|delete|public> [name]
    permission: xdbl.arena
  pvp:
    description: PVP command
    usage: /pvp <player|accept>
    permission: xdbl.pvp
  gvg:
    description: GVG command
    usage: /gvg <player|accept|invite>
    permission: xdbl.gvg
  mod:
    description: Moderation commands
    usage: /mod <ban> <arena|pvp> <player>
    permission: xdbl.mod
  top:
    description: Show the top fighters in the server
    usage: /top
    permission: xdbl.pvp
  leaderboard:
    description: Show the top fighters in the server
    usage: /top
    permission: xdbl.pvp
  profile:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
  stats:
    description: Show your profile
    usage: /profile
    permission: xdbl.pvp
  bidenblast:
    description: Channel bidens power to blast the enemy
    usage: /bidenblast
    permission: xdbl.pvp
