name: Build & Release

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get JAR filename
        id: get_jar_filename
        run: echo "::set-output name=jar_filename::$(basename $(find build/libs -name '*.jar') .jar)"
      - name: Upload release to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK }}
          filename: build/libs/${{ steps.get_jar_filename.outputs.jar_filename }}.jar
          content: |
            New `Nightly` build: ${{ steps.get_jar_filename.outputs.jar_filename }}
            This will contain the absolute latest changes and will not be stable.
            ```${{ github.event.head_commit.message }}```