name: Build & Release

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Build with Gradle Wrapper
        run: ./gradlew build --info --stacktrace
      - name: List build/libs directory
        run: ls -R build/libs
      - name: Get JAR filename
        id: get_jar_filename
        run: |
          jar_file=$(find build/libs -name '*.jar' -print -quit)
          if [ -z "$jar_file" ]; then
            echo "No JAR file found in build/libs directory"
            exit 1
          fi
          echo "JAR file found: $jar_file"
          jar_filename=$(basename "$jar_file")
          echo "JAR filename: $jar_filename"
          echo "::set-output name=jar_filename::$jar_filename"
      - name: Upload release to Discord
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK }}
          filename: build/libs/${{ steps.get_jar_filename.outputs.jar_filename }}
          content: |
            New Nightly build: `${{ steps.get_jar_filename.outputs.jar_filename }}`
            This will contain the absolute latest changes and will not be stable.
            ```${{ github.event.head_commit.message }}```
